name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: |
      github.event.issue.pull_request &&
      github.repository == 'adobe/react-spectrum' &&
      github.event.comment.author_association == 'MEMBER' &&
      contains(github.event.comment.body, 'GET_BUILD')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: yarn install
      - name: Check write permissions of commentor
        uses: ./.github/actions/permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create/update branch for fork PR
        uses: ./.github/actions/branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
